<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ram-PC" name="Default test" tests="5" failures="1" timestamp="20 Apr 2016 02:27:46 GMT" time="39.48" errors="0">
  <testcase name="autTC01" time="39.405" classname="com.flipkart.automation.tests.Sanity">
    <failure type="java.lang.AssertionError" message="expected [Mobiles - Buy Mobiles Online at Best Prices in India.] but found [Online Shopping India Mobile, Cameras, Lifestyle &amp;amp; more Online @ Flipkart.com]">
      <![CDATA[java.lang.AssertionError: expected [Mobiles - Buy Mobiles Online at Best Prices in India.] but found [Online Shopping India Mobile, Cameras, Lifestyle & more Online @ Flipkart.com]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.flipkart.automation.pages.Flipkart.verifyTitle(Flipkart.java:57)
	at com.flipkart.automation.tests.Sanity.autTC01(Sanity.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </failure>
  </testcase> <!-- autTC01 -->
  <testcase name="autTC02" time="0.001" classname="com.flipkart.automation.tests.Sanity"/>
  <testcase name="autTC03" time="0.001" classname="com.flipkart.automation.tests.Sanity"/>
  <testcase name="autTC04" time="0.002" classname="com.flipkart.automation.tests.Sanity"/>
  <testcase name="autTC05" time="0.001" classname="com.flipkart.automation.tests.Sanity"/>
</testsuite> <!-- Default test -->
